# Generated by Django 5.0.6 on 2024-08-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Reenterpassword', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('ReenterEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
